INSERT INTO tbl_cards (hp, name, type_id, stage_id, info, attack, dammage, weak, ressis, retreat, CardNumberInCollection, collection_id) VALUES
(50, 'Bulbasaur', 3, 1, 'Seed Pokémon. A strange seed was planted on its back at birth.', 'Vine Whip', 10, 'Fire', 'Water', 1, 44, 1),
(60, 'Ivysaur', 3, 2, 'Seed Pokémon. The bulb on its back grows by drawing energy.', 'Razor Leaf', 30, 'Fire', 'Water', 2, 45, 1),
(80, 'Venusaur', 3, 3, 'Seed Pokémon. Its plant blooms when it is absorbing solar energy.', 'SolarBeam', 60, 'Fire', 'Water', 4, 15, 1),
(40, 'Charmander', 1, 1, 'Lizard Pokémon. Breathes fire that is hot enough to melt boulders.', 'Ember', 10, 'Water', 'None', 1, 4, 1),
(50, 'Charmeleon', 1, 2, 'Flame Pokémon. When it swings its burning tail, it elevates the temperature.', 'Flamethrower', 30, 'Water', 'None', 2, 24, 1),
(80, 'Charizard', 1, 3, 'Flame Pokémon. Its wings can carry this Pokémon close to an altitude of 4,600 feet.', 'Fire Spin', 60, 'Water', 'None', 3, 6, 1),
(40, 'Squirtle', 2, 1, 'Tiny Turtle Pokémon. Shoots water at prey while in the water.', 'Water Gun', 10, 'Electric', 'None', 1, 7, 1),
(60, 'Wartortle', 2, 2, 'Turtle Pokémon. Often hides in water to stalk unwary prey.', 'Bubble Beam', 30, 'Electric', 'None', 2, 25, 1),
(100, 'Blastoise', 2, 3, 'Shellfish Pokémon. Once it takes aim at its enemy, it blasts out water.', 'Hydro Pump', 40, 'Electric', 'None', 3, 9, 1),
(60, 'Caterpie', 3, 1, 'Worm Pokémon. It releases a stench from its red antenna to repel enemies.', 'Tackle', 10, 'Fire', 'None', 1, 45, 1),
(40, 'Weedle', 3, 1, 'Hairy Bug Pokémon. Its poison stinger is very powerful.', 'Poison Sting', 10, 'Fire', 'None', 1, 50, 1),
(70, 'Pikachu', 4, 1, 'Mouse Pokémon. Stores electricity in its cheeks for zapping an enemy.', 'Thunder Shock', 30, 'Fighting', 'Steel', 1, 58, 1),
(50, 'Raichu', 4, 2, 'Mouse Pokémon. Its long tail serves as a ground to protect itself.', 'Thunder', 60, 'Fighting', 'Steel', 2, 26, 1),
(80, 'Jigglypuff', 4, 1, 'Balloon Pokémon. When its huge eyes light up, it sings a mysteriously soothing melody.', 'Pound', 20, 'Fighting', 'None', 1, 60, 2),
(40, 'Zubat', 4, 1, 'Bat Pokémon. Emits ultrasonic cries while it flies.', 'Bite', 10, 'Psychic', 'None', 1, 41, 2),
(50, 'Oddish', 3, 1, 'Weed Pokémon. Its scientific name is "Oddium Wanderus".', 'Absorb', 10, 'Fire', 'None', 1, 58, 2),
(60, 'Gloom', 3, 2, 'Weed Pokémon. The fluid that oozes from its mouth is a strong cell stimulant.', 'Poison Powder', 30, 'Fire', 'None', 2, 29, 2),
(70, 'Vileplume', 3, 3, 'Flower Pokémon. Its petals are the largest in the world.', 'Petal Dance', 40, 'Fire', 'None', 3, 13, 2),
(80, 'Paras', 3, 1, 'Mushroom Pokémon. Burrows to suck tree roots.', 'Scratch', 20, 'Fire', 'None', 1, 46, 2),
(90, 'Parasect', 3, 2, 'Mushroom Pokémon. The larger the mushroom on its back grows, the stronger the mushroom spores.', 'Leech Life', 30, 'Fire', 'None', 2, 47, 2),
(100, 'Venonat', 3, 1, 'Insect Pokémon. Its large eyes act as radar.', 'Poison Powder', 10, 'Fire', 'None', 1, 48, 2),
(110, 'Venomoth', 3, 2, 'Poison Moth Pokémon. Its wings are covered with dust-like scales.', 'Psybeam', 20, 'Fire', 'None', 2, 49, 2),
(120, 'Diglett', 4, 1, 'Mole Pokémon. Lives about one yard underground.', 'Scratch', 10, 'Water', 'None', 1, 50, 3),
(130, 'Dugtrio', 4, 2, 'Mole Pokémon. A team of Diglett triplets.', 'Earthquake', 60, 'Water', 'None', 2, 51, 3),
(140, 'Meowth', 4, 1, 'Scratch Cat Pokémon. Adores circular objects.', 'Pay Day', 20, 'Fighting', 'None', 1, 52, 3),
(150, 'Persian', 4, 2, 'Classy Cat Pokémon. The gem in its forehead glows on its own.', 'Slash', 50, 'Fighting', 'None', 2, 53, 3),
(160, 'Psyduck', 4, 1, 'Duck Pokémon. Always tormented by headaches.', 'Water Gun', 10, 'Electric', 'None', 1, 54, 3),
(170, 'Golduck', 4, 2, 'Duck Pokémon. A skilled swimmer.', 'Hydro Pump', 40, 'Electric', 'None', 2, 55, 3),
(180, 'Mankey', 4, 1, 'Pig Monkey Pokémon. Light and agile.', 'Karate Chop', 10, 'Psychic', 'None', 1, 56, 3);
