INSERT INTO tbl_cards (hp, name, type_id, stage_id, info, attack, dammage, weak, ressis, retreat, CardNumberInCollection, collection_id) VALUES
(90, 'Machoke', 6, 2, 'Superpower Pokémon. Its muscular body is so powerful.', 'Seismic Toss', 30, 'Psychic', 'None', 2, 67, 3),
(100, 'Machamp', 6, 3, 'Superpower Pokémon. It uses its four powerful arms to pin the limbs of its foe.', 'Submission', 40, 'Psychic', 'None', 3, 68, 3),
(40, 'Bellsprout', 3, 1, 'Flower Pokémon. Prefers hot and humid places.', 'Vine Whip', 10, 'Fire', 'None', 1, 69, 3),
(60, 'Weepinbell', 3, 2, 'Flycatcher Pokémon. It spits out poison powder to immobilize the enemy.', 'Razor Leaf', 20, 'Fire', 'None', 2, 70, 3),
(80, 'Victreebel', 3, 3, 'Flycatcher Pokémon. Lures prey with a sweet aroma.', 'SolarBeam', 50, 'Fire', 'None', 3, 71, 3),
(50, 'Tentacool', 2, 1, 'Jellyfish Pokémon. Drifts aimlessly in waves.', 'Poison Sting', 10, 'Electric', 'None', 1, 72, 3),
(70, 'Tentacruel', 2, 2, 'Jellyfish Pokémon. Moves silently through the sea.', 'Hydro Pump', 40, 'Electric', 'None', 2, 73, 3),
(40, 'Geodude', 6, 1, 'Rock Pokémon. Its round form makes it easy to roll.', 'Tackle', 10, 'Water', 'None', 1, 74, 3),
(60, 'Graveler', 6, 2, 'Rock Pokémon. Rolls down slopes to move.', 'Rock Throw', 20, 'Water', 'None', 2, 75, 3),
(80, 'Golem', 6, 3, 'Megaton Pokémon. Its boulder-like body withstands explosions.', 'Earthquake', 60, 'Water', 'None', 3, 76, 3),
(90, 'Ponyta', 1, 1, 'Fire Horse Pokémon. Capable of jumping incredibly high.', 'Flame Wheel', 20, 'Water', 'None', 1, 77, 3),
(100, 'Rapidash', 1, 2, 'Fire Horse Pokémon. Very competitive.', 'Fire Spin', 40, 'Water', 'None', 2, 78, 3),
(50, 'Slowpoke', 2, 1, 'Dopey Pokémon. Incredibly slow and dopey.', 'Water Gun', 10, 'Electric', 'None', 1, 79, 3),
(70, 'Slowbro', 2, 2, 'Hermit Crab Pokémon. Shellder latched onto its tail.', 'Surf', 30, 'Electric', 'None', 2, 80, 3),
(60, 'Magnemite', 4, 1, 'Magnet Pokémon. Its anti-gravity powers are limited.', 'Thunder Wave', 10, 'Fire', 'None', 1, 81, 3);
